[package]
name = "new_guessing_game"
version = "0.1.0"
authors = ["nilanj <ndjethwa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
